backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/blog" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets/blog"
collections:
  - name: "home"
    label: "Home"
    folder: "src/home"
    create: false # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Quote", name: "quote", widget: "string"}

  - name: "about"
    label: "About"
    folder: "src/about"
    create: false # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      
  - name: "quote"
    label: Quote
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Line", name: "line", widget: "string"}

  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", default: ["post"]}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Image caption", name: "imageAlt", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "product" # Used in routes, e.g., /admin/collections/blog
    label: "Product" # Used in the UI
    folder: "src/product" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", default: ["post"]}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Image caption", name: "imageAlt", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}